/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Jtest */

#ifndef _Included_Jtest
#define _Included_Jtest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Jtest
 * Method:    showhomo
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_Jtest_showhomo
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     Jtest
 * Method:    test1
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_Jtest_test1
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
